#!/usr/bin/env python3

import sys, os, tty, termios, argparse
from subprocess import run

parser = argparse.ArgumentParser(description="An interactive cli file viewer")
parser.add_argument('filename', help="The name of the file to view")

args = parser.parse_args()

tty.setcbreak(sys.stdin.fileno())

try:
    with open(args.filename) as f:
        input = f.read()
        output = input
except FileNotFoundError:
    print(f'File "{args.filename}" not found')
    sys.exit(1)

max_w = max([len(l) for l in input.split('\n')])

def h():
    return os.get_terminal_size().lines


def w():
    return os.get_terminal_size().columns


def process_char(c, ctx, force_execute=False):
    global output

    #  print(ctx['is_control_char'], ctx['is_arrow_key'])

    if ctx['is_arrow_key']:
        if c == chr(65):
            ctx['h_offset'] = max(0, ctx['h_offset'] - 3)
        elif c == chr(66):
            ctx['h_offset'] = max(0, min(len(output) - (h() - 2), ctx['h_offset'] + 3))
        elif c == chr(68):
            ctx['w_offset'] = max(0, ctx['w_offset'] - 10)
        elif c == chr(67):
            ctx['w_offset'] = max(0, min(max_w - w(), ctx['w_offset'] + 10))

    if ctx['is_control_char']:
        if c == chr(91):
            ctx['is_arrow_key'] = True
            return

    if c == chr(27):
        ctx['is_control_char'] = True

        return
    else:
        ctx['is_control_char'] = False

    command = ctx['command']

    if c == chr(127):
        command = command[:-1]
    elif not ctx['is_arrow_key'] and c != "\n":
        command += c

    ctx['is_arrow_key'] = False

    # Only run the subcommand if our command has changed
    # for scrolling performance
    error = None
    if force_execute or command != ctx['command']:
        try:
            proc = run((command or 'cat').split(' '),
                       capture_output=True,
                       input=input.encode('utf-8'))
            output = proc.stdout or proc.stderr
            output = output.decode('utf-8').split('\n')
        except (FileNotFoundError, PermissionError) as exc:
           error = exc

        ctx['command'] = command

    if error:
        print_command_output(str(error).split('\n'))
    else:
        print_command_output([
            line[ctx['w_offset']:w() + ctx['w_offset']]
            for line in output[ctx['h_offset']:]
        ])


def print_command_output(lines):
    os.system('clear')

    for i in range(0, h() - 2):
        try:
            print(lines[i])
        except IndexError:
            print("")

    sys.stdout.write('-' * w())
    sys.stdout.write("\n> " + ctx['command'])
    sys.stdout.flush()


ctx = {
    'command': '',
    'is_control_char': False,
    'is_arrow_key': False,
    'w_offset': 0,
    'h_offset': 0,
}

process_char('', ctx, force_execute=True)

while True:
    try:
        process_char(sys.stdin.read(1), ctx)
    except KeyboardInterrupt as exc:
        sys.exit(0)

